# Generated by Django 4.2.5 on 2023-10-09 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.TextField(max_length=18, unique=True)),
                ('password', models.CharField(max_length=33)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyManagment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('narx', models.IntegerField()),
                ('type_payment', models.CharField(choices=[('Kirim', 'Kirim'), ('Chiqim', 'Chiqim')], max_length=30)),
                ('type_expense', models.CharField(choices=[('Oziq ovqat', 'Oziq ovqat'), ('Transport', 'Transport'), ('Internet', 'Internet'), ('Telefon', 'Telefon'), ('kiyimlar', 'kiyimlar'), ('Qarzlar', 'Qarzlar'), ('Komunal', 'Komunal'), ('Boshqa', 'Boshqa')], max_length=30)),
                ('commentary', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.userregistration')),
            ],
        ),
    ]
